### ISSUE TITLE
Add libxlsxwriter topic to the project metadata

### ISSUE THREAD

**Issue by jmcnamara** [retsyo/libxlsxwriter_freebasic#1]
Hi,

Could you add libxlsxwriter as a "topic" metadata to your project so that users can find wrappers in different languages.

Topic/Metadata are shown at the top of the project: https://github.com/jmcnamara/libxlsxwriter

Other examples: https://github.com/search?q=topic%3Alibxlsxwriter&type=Repositories

Thanks,

John

**Comment by retsyo** [comment]
I can't edit the topic. everytime I click "manage topic", the loading-gif-icon runs and runs, and it does not enter the edit mode no matter in IE/FireFox on my notebook or PC.

**Comment by jmcnamara** [comment]
Ok. Thanks for trying. Closing.
